### ISSUE TITLE
cannot find object

### ISSUE THREAD

**Issue by DianaDeng** [drisso/fletcher2017data#1]
I have installed packages: clusterExperiment, devtools, SingleCellExperiment and fletcher2017data successfully and libraried them.
However I cannot find the object "fletcher" and "clustered".
![2018-09-29 7 36 42](https://user-images.githubusercontent.com/37362495/46252554-0911ec80-c41f-11e8-9660-0432535166db.png)

Is there something wrong with my package? As whenever I library it, it shows me many warnings.
![2018-09-29 7 37 38](https://user-images.githubusercontent.com/37362495/46252576-4b3b2e00-c41f-11e8-91db-6641fd40a0e6.png)
![2018-09-29 7 38 03](https://user-images.githubusercontent.com/37362495/46252577-4f674b80-c41f-11e8-86dd-fddc2faab97b.png)
![2018-09-29 7 38 25](https://user-images.githubusercontent.com/37362495/46252578-54c49600-c41f-11e8-8d02-ae5434151eef.png)

**Comment by drisso** [comment]
This package does not have lazy loading of the objects. You need to manually load the object with

```{r}
data(fletcher)
data(clustered)
```

to be able to use the objects.

**Comment by luoyuan1984** [comment]
> I have installed packages: clusterExperiment, devtools, SingleCellExperiment and fletcher2017data successfully and libraried them.
> However I cannot find the object "fletcher" and "clustered".
> ![2018-09-29 7 36 42](https://user-images.githubusercontent.com/37362495/46252554-0911ec80-c41f-11e8-9660-0432535166db.png)
> 
> Is there something wrong with my package? As whenever I library it, it shows me many warnings.
> ![2018-09-29 7 37 38](https://user-images.githubusercontent.com/37362495/46252576-4b3b2e00-c41f-11e8-91db-6641fd40a0e6.png)
> ![2018-09-29 7 38 03](https://user-images.githubusercontent.com/37362495/46252577-4f674b80-c41f-11e8-86dd-fddc2faab97b.png)
> ![2018-09-29 7 38 25](https://user-images.githubusercontent.com/37362495/46252578-54c49600-c41f-11e8-8d02-ae5434151eef.png)

Hi, would you please show me how to install 'fletcher2017data' package? Thank you.
